apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-deploy
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-global
spec:
  gatewayClassName: eg-deploy
  listeners:
    - name: http
      allowedRoutes:
            namespaces:
              from: All        
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      hostname: "*.deploy.lightup.tw"
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: eg-deploy-https          