apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kratos
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - list:
            elements:
            - tenantId: qw12123   
            # - tenantId: asdasdas123
        - clusters: {}
        # - list:
        #     elements:
        #     - cluster: gke_lightup-tw_asia-east1_development
        #     - cluster:  https://kubernetes.default.svc
  template:
      metadata:
          name: "{{.name}}-kratos-{{.tenantId}}"
          namespace: argo-cd
      spec:
            project: kratos
            syncPolicy:
                syncOptions:
                - CreateNamespace=true
                managedNamespaceMetadata:
                    labels: 
                        kratos: "true"
                        tenantId: "{{.tenantId}}"     
                    # annotations: # The annotations to set on the application namespace
                    #     the: same
                    #     applies: for
                    #     annotations: on-the-namespace                                

            sources:
              - repoURL: https://k8s.ory.sh/helm/charts
                chart: kratos
                targetRevision: "0.44.0"
                helm:
                    releaseName: kratos   
                    valuesObject:
                        courier:
                            enabled: false
                        kratos:
                            configmap:
                                dsn: postgres://foo:bar@pg-sqlproxy-gcloud-sqlproxy:5432/db
                                secrets:
                                default:
                                    - dolore occaecat nostrud Ut
                                    - sit et commodoaute ut voluptate consectetur Duis
                                identity:
                                default_schema_id: default
                                schemas:
                                    - id: default
                                      url: file:///etc/config/identity.default.schema.json
                                courier:
                                smtp:
                                    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
                                selfservice:
                                default_browser_return_url: http://127.0.0.1:4455/
                            automigration:
                                enabled: true
                            identitySchemas:
                                "identity.default.schema.json": |
                                    {
                                    "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
                                    "$schema": "http://json-schema.org/draft-07/schema#",
                                    "title": "Person",
                                    "type": "object",
                                    "properties": {
                                    "traits": {
                                        "type": "object",
                                        "properties": {
                                        "email": {
                                            "type": "string",
                                            "format": "email",
                                            "title": "E-Mail",
                                            "ory.sh/kratos": {
                                            "credentials": {
                                                "password": {
                                                "identifier": true
                                                }
                                            },
                                            "recovery": {
                                                "via": "email"
                                            },
                                            "verification": {
                                                "via": "email"
                                            }
                                            }
                                        }
                                        },
                                        "required": [
                                        "email"
                                        ],
                                        "additionalProperties": false
                                    }
                                    }
                                    }                            
                        deployment:
                            extraEnv:
                                - name: DSN
                                  value: "postgres://postgres:password@10.70.79.203:5432/kratos"
                            #   valueFrom:
                            #     secretKeyRef:
                            #     name: dsn-secret
                            #     key: dsn
            destination:
                server: "{{.server}}"
                namespace: kratos-{{.tenantId}}