# - name: Deploy RKE2
#   # hosts: k8s_cluster
#   hosts: rke21
#   become: yes
#   # vars:
#     # rke2_airgap_mode: true
#     # rke2_airgap_implementation: download
#   #   rke2_ha_mode: true
#   #   rke2_api_ip: 192.168.100.6
#   #   rke2_download_kubeconf: true
#   roles:
#     - role: lablabs.rke2
# - name: Deploy RKE2
#   hosts: k8s_cluster
#   become: yes
#   roles:
#     - role: lablabs.rke2
- name: Deploy RKE2
  hosts: k8s_cluster
  become: true
  roles:
    - role: lablabs.rke2
  vars:
    rke2_type: server
    rke2_version: v1.30.4+rke2r1
    rke2_ha_mode: true
    rke2_api_ip: 10.10.2.100

    # rke2_disable:
    #   - rke2-ingress-nginx
    #   - rke2-canal
    # disable_kube_proxy: true
    rke2_cni:
      - cilium
    rke2_download_kubeconf: true
    rke2_ingress_nginx_values: 
      controller:
          config:
            use-forwarded-headers: "true"
            enable-real-ip: "true"
          publishService:
            enabled: true
          service:
            enabled: true
            type: LoadBalancer
            externalTrafficPolicy: Local
            annotations:
              metallb.universe.tf/loadBalancerIPs: 10.10.2.20
      
   
    rke2_cluster_cidr:
      - 192.42.0.0/16            
    rke2_service_cidr:
      - 192.43.0.0/16      

